name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
      - name: Check the reference variables
        run: |
          echo "GITHUB_REF:" + ${{ GITHUB_REF }}
          echo "GITHUB.EVENT.PUSH_REF:" + ${{ github.event.push.ref }} 
